/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents.index'
import { Route as AuthenticatedReportsSignersRouteImport } from './routes/_authenticated/reports.signers'
import { Route as AuthenticatedReportsDocumentsRouteImport } from './routes/_authenticated/reports.documents'
import { Route as AuthenticatedReportsCompetenciasRouteImport } from './routes/_authenticated/reports.competencias'
import { Route as AuthenticatedReportsAuditRouteImport } from './routes/_authenticated/reports.audit'
import { Route as AuthenticatedDocumentsNewRouteImport } from './routes/_authenticated/documents.new'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'
import { Route as ApiPublicFaceVerifyRouteImport } from './routes/api/public/face/verify'
import { Route as ApiPublicFaceRegisterRouteImport } from './routes/api/public/face/register'
import { Route as ApiPublicSignTokenIndexRouteImport } from './routes/api/public/sign/$token/index'
import { Route as ApiPublicSignTokenConfirmRouteImport } from './routes/api/public/sign/$token/confirm'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsSignersRoute =
  AuthenticatedReportsSignersRouteImport.update({
    id: '/signers',
    path: '/signers',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsDocumentsRoute =
  AuthenticatedReportsDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsCompetenciasRoute =
  AuthenticatedReportsCompetenciasRouteImport.update({
    id: '/competencias',
    path: '/competencias',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsAuditRoute =
  AuthenticatedReportsAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedDocumentsNewRoute =
  AuthenticatedDocumentsNewRouteImport.update({
    id: '/documents/new',
    path: '/documents/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/documents/$id',
    path: '/documents/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicFaceVerifyRoute = ApiPublicFaceVerifyRouteImport.update({
  id: '/api/public/face/verify',
  path: '/api/public/face/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFaceRegisterRoute = ApiPublicFaceRegisterRouteImport.update({
  id: '/api/public/face/register',
  path: '/api/public/face/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSignTokenIndexRoute = ApiPublicSignTokenIndexRouteImport.update({
  id: '/api/public/sign/$token/',
  path: '/api/public/sign/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSignTokenConfirmRoute =
  ApiPublicSignTokenConfirmRouteImport.update({
    id: '/api/public/sign/$token/confirm',
    path: '/api/public/sign/$token/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/sign/$token': typeof SignTokenRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/reports/audit': typeof AuthenticatedReportsAuditRoute
  '/reports/competencias': typeof AuthenticatedReportsCompetenciasRoute
  '/reports/documents': typeof AuthenticatedReportsDocumentsRoute
  '/reports/signers': typeof AuthenticatedReportsSignersRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/api/public/face/register': typeof ApiPublicFaceRegisterRoute
  '/api/public/face/verify': typeof ApiPublicFaceVerifyRoute
  '/api/public/sign/$token/confirm': typeof ApiPublicSignTokenConfirmRoute
  '/api/public/sign/$token/': typeof ApiPublicSignTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sign/$token': typeof SignTokenRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/reports/audit': typeof AuthenticatedReportsAuditRoute
  '/reports/competencias': typeof AuthenticatedReportsCompetenciasRoute
  '/reports/documents': typeof AuthenticatedReportsDocumentsRoute
  '/reports/signers': typeof AuthenticatedReportsSignersRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/api/public/face/register': typeof ApiPublicFaceRegisterRoute
  '/api/public/face/verify': typeof ApiPublicFaceVerifyRoute
  '/api/public/sign/$token/confirm': typeof ApiPublicSignTokenConfirmRoute
  '/api/public/sign/$token': typeof ApiPublicSignTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/sign/$token': typeof SignTokenRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/_authenticated/reports/audit': typeof AuthenticatedReportsAuditRoute
  '/_authenticated/reports/competencias': typeof AuthenticatedReportsCompetenciasRoute
  '/_authenticated/reports/documents': typeof AuthenticatedReportsDocumentsRoute
  '/_authenticated/reports/signers': typeof AuthenticatedReportsSignersRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/api/public/face/register': typeof ApiPublicFaceRegisterRoute
  '/api/public/face/verify': typeof ApiPublicFaceVerifyRoute
  '/api/public/sign/$token/confirm': typeof ApiPublicSignTokenConfirmRoute
  '/api/public/sign/$token/': typeof ApiPublicSignTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/oauth-callback'
    | '/reset-password'
    | '/clients'
    | '/dashboard'
    | '/history'
    | '/reports'
    | '/settings'
    | '/sign/$token'
    | '/documents/$id'
    | '/documents/new'
    | '/reports/audit'
    | '/reports/competencias'
    | '/reports/documents'
    | '/reports/signers'
    | '/documents/'
    | '/reports/'
    | '/api/public/face/register'
    | '/api/public/face/verify'
    | '/api/public/sign/$token/confirm'
    | '/api/public/sign/$token/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/oauth-callback'
    | '/reset-password'
    | '/clients'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/sign/$token'
    | '/documents/$id'
    | '/documents/new'
    | '/reports/audit'
    | '/reports/competencias'
    | '/reports/documents'
    | '/reports/signers'
    | '/documents'
    | '/reports'
    | '/api/public/face/register'
    | '/api/public/face/verify'
    | '/api/public/sign/$token/confirm'
    | '/api/public/sign/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/oauth-callback'
    | '/reset-password'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/sign/$token'
    | '/_authenticated/documents/$id'
    | '/_authenticated/documents/new'
    | '/_authenticated/reports/audit'
    | '/_authenticated/reports/competencias'
    | '/_authenticated/reports/documents'
    | '/_authenticated/reports/signers'
    | '/_authenticated/documents/'
    | '/_authenticated/reports/'
    | '/api/public/face/register'
    | '/api/public/face/verify'
    | '/api/public/sign/$token/confirm'
    | '/api/public/sign/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignTokenRoute: typeof SignTokenRoute
  ApiPublicFaceRegisterRoute: typeof ApiPublicFaceRegisterRoute
  ApiPublicFaceVerifyRoute: typeof ApiPublicFaceVerifyRoute
  ApiPublicSignTokenConfirmRoute: typeof ApiPublicSignTokenConfirmRoute
  ApiPublicSignTokenIndexRoute: typeof ApiPublicSignTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/signers': {
      id: '/_authenticated/reports/signers'
      path: '/signers'
      fullPath: '/reports/signers'
      preLoaderRoute: typeof AuthenticatedReportsSignersRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/documents': {
      id: '/_authenticated/reports/documents'
      path: '/documents'
      fullPath: '/reports/documents'
      preLoaderRoute: typeof AuthenticatedReportsDocumentsRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/competencias': {
      id: '/_authenticated/reports/competencias'
      path: '/competencias'
      fullPath: '/reports/competencias'
      preLoaderRoute: typeof AuthenticatedReportsCompetenciasRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/audit': {
      id: '/_authenticated/reports/audit'
      path: '/audit'
      fullPath: '/reports/audit'
      preLoaderRoute: typeof AuthenticatedReportsAuditRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/documents/new': {
      id: '/_authenticated/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AuthenticatedDocumentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/face/verify': {
      id: '/api/public/face/verify'
      path: '/api/public/face/verify'
      fullPath: '/api/public/face/verify'
      preLoaderRoute: typeof ApiPublicFaceVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/face/register': {
      id: '/api/public/face/register'
      path: '/api/public/face/register'
      fullPath: '/api/public/face/register'
      preLoaderRoute: typeof ApiPublicFaceRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sign/$token/': {
      id: '/api/public/sign/$token/'
      path: '/api/public/sign/$token'
      fullPath: '/api/public/sign/$token/'
      preLoaderRoute: typeof ApiPublicSignTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sign/$token/confirm': {
      id: '/api/public/sign/$token/confirm'
      path: '/api/public/sign/$token/confirm'
      fullPath: '/api/public/sign/$token/confirm'
      preLoaderRoute: typeof ApiPublicSignTokenConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsAuditRoute: typeof AuthenticatedReportsAuditRoute
  AuthenticatedReportsCompetenciasRoute: typeof AuthenticatedReportsCompetenciasRoute
  AuthenticatedReportsDocumentsRoute: typeof AuthenticatedReportsDocumentsRoute
  AuthenticatedReportsSignersRoute: typeof AuthenticatedReportsSignersRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsAuditRoute: AuthenticatedReportsAuditRoute,
  AuthenticatedReportsCompetenciasRoute: AuthenticatedReportsCompetenciasRoute,
  AuthenticatedReportsDocumentsRoute: AuthenticatedReportsDocumentsRoute,
  AuthenticatedReportsSignersRoute: AuthenticatedReportsSignersRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
  AuthenticatedDocumentsNewRoute: typeof AuthenticatedDocumentsNewRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  AuthenticatedDocumentsNewRoute: AuthenticatedDocumentsNewRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignTokenRoute: SignTokenRoute,
  ApiPublicFaceRegisterRoute: ApiPublicFaceRegisterRoute,
  ApiPublicFaceVerifyRoute: ApiPublicFaceVerifyRoute,
  ApiPublicSignTokenConfirmRoute: ApiPublicSignTokenConfirmRoute,
  ApiPublicSignTokenIndexRoute: ApiPublicSignTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
